FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

# Imagen para compilar
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiar archivos de proyecto
COPY ["TMS.Web.API/TMS.Web.API.csproj", "TMS.Web.API/"]
COPY ["TMS.Application/TMS.Application.csproj", "TMS.Application/"]
COPY ["TMS.Domain/TMS.Domain.csproj", "TMS.Domain/"]
COPY ["TMS.Infrastructure/TMS.Infrastructure.csproj", "TMS.Infrastructure/"]

# Restaurar dependencies
RUN dotnet restore "TMS.Web.API/TMS.Web.API.csproj"

# Copiar código y compilar
COPY . .
RUN dotnet publish "TMS.Web.API/TMS.Web.API.csproj" -c Release -o /app/publish

# Imagen final
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "TMS.Web.API.dll"]